'use strict';
const R=window.RESTAURANTS,C=window.APP_CONFIG,$=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=new URLSearchParams(location.hash.slice(1)).get('token')||'';
const online=Boolean(C.supabaseUrl&&C.supabaseKey), storageKey=token?'wz-'+token:'wz-demo';
let local={name:'',ratings:{},favorite:null},team=[],filter='Wszystkie',dirty=false,busy=false;
try{local={...local,...JSON.parse(localStorage.getItem(storageKey)||'{}')}}catch{}
$('#name').value=local.name;
function toast(s){$('#status').textContent=s;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#status').textContent='',6000)}
function remember(){dirty=true;try{localStorage.setItem(storageKey,JSON.stringify(local))}catch{}$('#savehint').textContent='Masz niezapisane zmiany.'}
function cards(){
 $('#progress').textContent=Object.keys(local.ratings).length+' / 9 ocenionych';
 $('#cards').innerHTML=R.filter(r=>filter==='Wszystkie'||r.town===filter||r.tags.includes(filter)).map(r=>{
 const groups=[...new Set(r.menu.map(m=>m.category))];
 const menu=groups.map(g=>`<div class="menu-group"><h4>${esc(g)}</h4>${r.menu.filter(m=>m.category===g).map(m=>`<p><span>${esc(m.name)}</span><b>${m.price} zł</b></p>`).join('')}</div>`).join('');
 return `<article class="card"><div class="cardtop"><span class="town">${esc(r.town)}</span><h3>${esc(r.name)}</h3><div class="tags">${r.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><p class="description">${esc(r.desc)}</p><ul class="preview">${r.menu.slice(0,3).map(m=>`<li><span>${esc(m.name)}</span><b>${m.price} zł</b></li>`).join('')||'<li>Menu do uzupełnienia</li>'}</ul></div><details><summary>${r.assets.length?'Zobacz menu':'Zobacz dostępne pozycje'}</summary>${menu}<p class="source">${esc(r.source)}</p>${r.assets.map((a,i)=>`<p><a href="${a}" target="_blank" rel="noopener noreferrer">Oryginalna karta ${i+1}</a></p>`).join('')}</details><div class="links">${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Strona / menu restauracji</a>`:'<span class="source">Brak potwierdzonego linku oficjalnego</span>'}<a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.name+' '+r.town)}" target="_blank" rel="noopener noreferrer">Mapa</a></div><div class="votes" data-id="${r.id}">${[[2,'😍 Chcę tam'],[1,'🙂 Może być'],[0,'✕ Odpada']].map(([v,l])=>`<button data-score="${v}" aria-pressed="${local.ratings[r.id]===v}" class="${local.ratings[r.id]===v?'active':''}">${l}</button>`).join('')}<button class="favorite ${local.favorite===r.id?'active':''}" data-favorite aria-pressed="${local.favorite===r.id}">☆ ${local.favorite===r.id?'Mój faworyt':'Wybierz faworyta'}</button></div></article>`;
 }).join('');
}
const filters=['Wszystkie','Tleń','Syto','Elegancko','Dobra cena','Dziczyzna','Ryby'];
function drawFilters(){$('#filters').innerHTML=filters.map(f=>`<button data-filter="${f}" class="${f===filter?'active':''}" aria-pressed="${f===filter}">${f}</button>`).join('')}
$('#filters').onclick=e=>{if(e.target.dataset.filter){filter=e.target.dataset.filter;drawFilters();cards()}};
$('#cards').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.closest('.votes').dataset.id;if(b.hasAttribute('data-score')){const v=Number(b.dataset.score);if(local.ratings[id]===v)delete local.ratings[id];else local.ratings[id]=v;if(local.favorite===id&&local.ratings[id]!==2)local.favorite=null}else{local.favorite=local.favorite===id?null:id;if(local.favorite)local.ratings[id]=2}remember();cards()};
$('#name').oninput=e=>{local.name=e.target.value;remember()};
function rankings(){const ranked=R.map(r=>{const rated=team.filter(v=>Object.hasOwn(v.ratings,r.id));return {...r,points:rated.reduce((s,v)=>s+v.ratings[r.id],0),count:rated.length,no:rated.filter(v=>v.ratings[r.id]===0).length,favs:team.filter(v=>v.favorite===r.id).length}}).sort((a,b)=>b.points-a.points||b.favs-a.favs||a.name.localeCompare(b.name,'pl'));
 $('#ranking').innerHTML=ranked.map((r,i)=>`<div class="rank"><b>${i+1}.</b><div><strong>${esc(r.name)}</strong><br><small>${r.count}/4 ocen · ${r.no} odpada · ${r.favs} faworytów</small><div class="bar"><i style="width:${r.points/8*100}%"></i></div></div><b>${r.points}/8 pkt</b></div>`).join('');
 $('#results-note').textContent=online?`${team.filter(v=>Object.keys(v.ratings).length).length}/4 osób zapisało oceny. Wyniki odświeżane co 20 sekund.`:'Podgląd: wyniki dotyczą tylko Twojego zapisanego głosu na tym urządzeniu.';
 $('#matrix').innerHTML='<table><thead><tr><th>Restauracja</th>'+team.map(v=>`<th>${esc(v.name)}</th>`).join('')+'</tr></thead><tbody>'+R.map(r=>'<tr><th>'+esc(r.name)+'</th>'+team.map(v=>`<td>${['✕','🙂','😍'][v.ratings[r.id]]||'—'}${v.favorite===r.id?' ☆':''}</td>`).join('')+'</tr>').join('')+'</tbody></table>';
}
async function rpc(name,body){const response=await fetch(C.supabaseUrl.replace(/\/$/,'')+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:C.supabaseKey,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});if(!response.ok){let msg='Nie udało się połączyć z bazą ('+response.status+').';try{msg=(await response.json()).message||msg}catch{}throw Error(msg)}return response.json()}
async function refresh(loadMine=false){if(!online){team=local.name.trim()&&local.saved?[{...local,name:local.name.trim()}]:[];rankings();return}if(!token){$('#connection').textContent='Otwórz swój osobisty link od organizatora. Menu możesz przeglądać bez niego.';return}try{const result=await rpc('zarlo_results',{p_token:token});team=result.team;if(loadMine&&!dirty){local={...result.mine};$('#name').value=local.name;cards()}rankings();$('#connection').textContent='Połączono. Twoje zapisane oceny widzi cała ekipa.'}catch(e){$('#connection').textContent='Brak połączenia: '+e.message;if(loadMine)toast('Nie pobrano głosów. Twoje zmiany pozostają na urządzeniu.')}}
$('#save').onclick=async()=>{if(busy)return;if(!local.name.trim()){toast('Wpisz imię lub pseudonim.');$('#name').focus();return}if(!Object.keys(local.ratings).length){toast('Oceń przynajmniej jedną restaurację.');return}if(online&&!token){toast('Do zapisu potrzebujesz osobistego linku od organizatora.');return}busy=true;$('#save').disabled=true;try{if(online)await rpc('zarlo_save',{p_token:token,p_name:local.name.trim(),p_ratings:local.ratings,p_favorite:local.favorite});local.saved=true;try{localStorage.setItem(storageKey,JSON.stringify(local))}catch{}dirty=false;$('#savehint').textContent=online?'Głos zapisany dla ekipy.':'Zapisano lokalnie na tym urządzeniu.';toast(online?'Zapisano! Możesz zmienić zdanie w każdej chwili.':'Zapisano w podglądzie lokalnym.');await refresh()}catch(e){toast('Nie zapisano: '+e.message)}finally{busy=false;$('#save').disabled=false}};
$('#refresh').onclick=()=>refresh();$('#mode').textContent=online?'Wspólne głosowanie':'Podgląd lokalny';$('#connection').textContent=online?'Łączenie…':'Wspólne wyniki będą dostępne po konfiguracji opisanej w instrukcji.';drawFilters();cards();refresh(true);if(online)setInterval(()=>{if(!document.hidden)refresh()},20000);
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
